//
// Generated file, do not edit! Created by nedtool 4.6 from src/EdgeNode/OBS_BurstifierInfo.msg.
//

#ifndef _OBS_BURSTIFIERINFO_M_H_
#define _OBS_BURSTIFIERINFO_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/EdgeNode/OBS_BurstifierInfo.msg:23</tt> by nedtool.
 * <pre>
 * // Additional burst control info included in OBS_PacketBurstifier and OBS_FileBurstifier.
 * class OBS_BurstifierInfo
 * {
 *     int label = -1; // Destination label.
 * }
 * </pre>
 */
class OBS_BurstifierInfo : public ::cObject
{
  protected:
    int label_var;

  private:
    void copy(const OBS_BurstifierInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_BurstifierInfo&);

  public:
    OBS_BurstifierInfo();
    OBS_BurstifierInfo(const OBS_BurstifierInfo& other);
    virtual ~OBS_BurstifierInfo();
    OBS_BurstifierInfo& operator=(const OBS_BurstifierInfo& other);
    virtual OBS_BurstifierInfo *dup() const {return new OBS_BurstifierInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getLabel() const;
    virtual void setLabel(int label);
};

inline void doPacking(cCommBuffer *b, OBS_BurstifierInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OBS_BurstifierInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OBS_BURSTIFIERINFO_M_H_

