//
// Generated file, do not edit! Created by nedtool 4.6 from src/EdgeNode/OBS_ScheduledBurstItem.msg.
//

#ifndef _OBS_SCHEDULEDBURSTITEM_M_H_
#define _OBS_SCHEDULEDBURSTITEM_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/EdgeNode/OBS_ScheduledBurstItem.msg:23</tt> by nedtool.
 * <pre>
 * // Burst container for BurstList.
 * packet OBS_ScheduledBurstItem
 * {
 *     int listIndex = -1; //Index field used by BurstList. opp_neddoc complains if named 'index'.
 *     int burstId = -1; //Burst Id.
 *     simtime_t sendTime = -1; //Time scheduled to send the burst.
 *     simtime_t minOffset = -1; //Minimum offset.
 *     simtime_t maxOffset = -1; //Maximum offset.
 * }
 * </pre>
 */
class OBS_ScheduledBurstItem : public ::cPacket
{
  protected:
    int listIndex_var;
    int burstId_var;
    simtime_t sendTime_var;
    simtime_t minOffset_var;
    simtime_t maxOffset_var;

  private:
    void copy(const OBS_ScheduledBurstItem& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_ScheduledBurstItem&);

  public:
    OBS_ScheduledBurstItem(const char *name=NULL, int kind=0);
    OBS_ScheduledBurstItem(const OBS_ScheduledBurstItem& other);
    virtual ~OBS_ScheduledBurstItem();
    OBS_ScheduledBurstItem& operator=(const OBS_ScheduledBurstItem& other);
    virtual OBS_ScheduledBurstItem *dup() const {return new OBS_ScheduledBurstItem(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getListIndex() const;
    virtual void setListIndex(int listIndex);
    virtual int getBurstId() const;
    virtual void setBurstId(int burstId);
    virtual simtime_t getSendTime() const;
    virtual void setSendTime(simtime_t sendTime);
    virtual simtime_t getMinOffset() const;
    virtual void setMinOffset(simtime_t minOffset);
    virtual simtime_t getMaxOffset() const;
    virtual void setMaxOffset(simtime_t maxOffset);
};

inline void doPacking(cCommBuffer *b, OBS_ScheduledBurstItem& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OBS_ScheduledBurstItem& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OBS_SCHEDULEDBURSTITEM_M_H_

