//
// Generated file, do not edit! Created by nedtool 4.6 from src/CoreNode/OBS_BCPControlInfo.msg.
//

#ifndef _OBS_BCPCONTROLINFO_M_H_
#define _OBS_BCPCONTROLINFO_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/CoreNode/OBS_BCPControlInfo.msg:23</tt> by nedtool.
 * <pre>
 * // Control info object included in OBS_BurstControlPacket when converted to electrical.
 * class OBS_BCPControlInfo
 * {
 *     int port = -1; // BCP input/output fiber.
 *     simtime_t BCPArrival = -1; // BCPini arrival time.
 * }
 * </pre>
 */
class OBS_BCPControlInfo : public ::cObject
{
  protected:
    int port_var;
    simtime_t BCPArrival_var;

  private:
    void copy(const OBS_BCPControlInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_BCPControlInfo&);

  public:
    OBS_BCPControlInfo();
    OBS_BCPControlInfo(const OBS_BCPControlInfo& other);
    virtual ~OBS_BCPControlInfo();
    OBS_BCPControlInfo& operator=(const OBS_BCPControlInfo& other);
    virtual OBS_BCPControlInfo *dup() const {return new OBS_BCPControlInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPort() const;
    virtual void setPort(int port);
    virtual simtime_t getBCPArrival() const;
    virtual void setBCPArrival(simtime_t BCPArrival);
};

inline void doPacking(cCommBuffer *b, OBS_BCPControlInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OBS_BCPControlInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OBS_BCPCONTROLINFO_M_H_

