//
// Generated file, do not edit! Created by nedtool 4.6 from src/Retransmit/OBS_RetransmitPacket.msg.
//

#ifndef _OBS_RETRANSMITPACKET_M_H_
#define _OBS_RETRANSMITPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/Retransmit/OBS_RetransmitPacket.msg:32</tt> by nedtool.
 * <pre>
 * // Request and acknowledgement of the bufferless retransmission baseline (paper section 5.2).
 * //
 * // The baseline recovers contention loss in the time domain instead of the optical domain: the
 * // core drops the burst, the source sees no acknowledgement within retransmitTimeout and sends
 * // the packet again, up to maxRetransmissions times. The sequence number is what pairs an
 * // acknowledgement with the request it answers.
 * //
 * // It is a field of the packet rather than bytes inside a payload because the edge burstifier
 * // wraps whole packets: a payload would have to be re-parsed byte-wise on reception, and the
 * // acknowledgement is a different size from the request anyway.
 * packet OBS_RetransmitPacket
 * {
 *     int seq = -1; //Request sequence number. The acknowledgement echoes the number it answers.
 * }
 * </pre>
 */
class OBS_RetransmitPacket : public ::cPacket
{
  protected:
    int seq_var;

  private:
    void copy(const OBS_RetransmitPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_RetransmitPacket&);

  public:
    OBS_RetransmitPacket(const char *name=NULL, int kind=0);
    OBS_RetransmitPacket(const OBS_RetransmitPacket& other);
    virtual ~OBS_RetransmitPacket();
    OBS_RetransmitPacket& operator=(const OBS_RetransmitPacket& other);
    virtual OBS_RetransmitPacket *dup() const {return new OBS_RetransmitPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSeq() const;
    virtual void setSeq(int seq);
};

inline void doPacking(cCommBuffer *b, OBS_RetransmitPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OBS_RetransmitPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OBS_RETRANSMITPACKET_M_H_

