//
// Generated file, do not edit! Created by nedtool 4.6 from src/tests/sources/SourceControlInfo.msg.
//

#ifndef _SOURCECONTROLINFO_M_H_
#define _SOURCECONTROLINFO_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/tests/sources/SourceControlInfo.msg:24</tt> by nedtool.
 * <pre>
 * //Control info to attach to the scheduled objects with the index of OMNeT++ gate where the object will be sent by.
 * //Used in testSource2, testSource3, testSource4.
 * class SourceControlInfo
 * {
 *     int sendingIndex = -1;
 *     int label = -1; //Only for testSource2
 * }
 * </pre>
 */
class SourceControlInfo : public ::cObject
{
  protected:
    int sendingIndex_var;
    int label_var;

  private:
    void copy(const SourceControlInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SourceControlInfo&);

  public:
    SourceControlInfo();
    SourceControlInfo(const SourceControlInfo& other);
    virtual ~SourceControlInfo();
    SourceControlInfo& operator=(const SourceControlInfo& other);
    virtual SourceControlInfo *dup() const {return new SourceControlInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSendingIndex() const;
    virtual void setSendingIndex(int sendingIndex);
    virtual int getLabel() const;
    virtual void setLabel(int label);
};

inline void doPacking(cCommBuffer *b, SourceControlInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SourceControlInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SOURCECONTROLINFO_M_H_

